[6.x] Add support for PHPUnit v10
laravel/browser-kit-testing pull request #153
Opened 2021-01-28 13:34 UTC by driesvints

2021-01-28 13:36 UTC, GrahamCampbell requested changes

2021-01-28 13:36 UTC, GrahamCampbell commented on .github/workflows/tests.yml
> +        phpunit: [^8.4, ^9.0, ^10.0]
`^8.5` would match the require block.

2021-01-28 13:46 UTC, driesvints commented on .github/workflows/tests.yml
> +        phpunit: [^8.4, ^9.0, ^10.0]
Good one

2021-09-02 09:28 UTC, driesvints commented
Closing this until we have more news about PHPUnit 10's release date.

2021-09-02 09:28 UTC, closed without merging